### ISSUE TITLE
missing install instructions

### ISSUE THREAD

**Issue by carocad** [scriptharness/python-scriptharness#27]
Hey Aki,
I saw that scriptharness is already on Pypi. Don't you think it would be nice to have some installation instructions on the README of scriptharness?

**Comment by escapewindow** [comment]
It's got a setup.py that behaves in a standard fashion afaict.  Is there something special you had in mind?

**Comment by carocad** [comment]
yeah, since scriptharness is already in Pypi, I thought that putting a very simple installation instruction would link them together in a more clear fashion; just plug and play.

### install

```
pip install scriptharness
```

### Requirements
- this
- and that

PS: The homepage link in pypi (gotten from setup.py) is broken. I guess you changed the name from scriptharness to python-scriptharness.
